// <auto-generated />
using System;
using CS.Session.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS.Session.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241029171719_AddAudits")]
    partial class AddAudits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CS.Session.Domain.Sessions.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MediaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            
                            EndTime = new DateTime(2024, 10, 29, 17, 13, 18, 915, DateTimeKind.Local).AddTicks(4920),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 10, 29, 14, 37, 18, 915, DateTimeKind.Local).AddTicks(4920),
                            State = "CLOSED",
                            UserId = 8
                        },
                        new
                        {
                            Id = 2L,
                            
                            EndTime = new DateTime(2024, 10, 29, 15, 55, 18, 915, DateTimeKind.Local).AddTicks(5024),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 10, 29, 14, 32, 18, 915, DateTimeKind.Local).AddTicks(5024),
                            State = "CLOSED",
                            UserId = 10
                        },
                        new
                        {
                            Id = 3L,
                            
                            EndTime = new DateTime(2024, 10, 29, 14, 30, 18, 915, DateTimeKind.Local).AddTicks(5042),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 10, 29, 13, 45, 18, 915, DateTimeKind.Local).AddTicks(5042),
                            State = "CLOSED",
                            UserId = 9
                        },
                        new
                        {
                            Id = 4L,
                            
                            EndTime = new DateTime(2024, 10, 29, 17, 8, 18, 915, DateTimeKind.Local).AddTicks(5056),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 10, 29, 14, 28, 18, 915, DateTimeKind.Local).AddTicks(5056),
                            State = "CLOSED",
                            UserId = 10
                        },
                        new
                        {
                            Id = 5L,
                            
                            EndTime = new DateTime(2024, 10, 29, 15, 29, 18, 915, DateTimeKind.Local).AddTicks(5071),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 10, 29, 14, 34, 18, 915, DateTimeKind.Local).AddTicks(5071),
                            State = "CLOSED",
                            UserId = 7
                        },
                        new
                        {
                            Id = 6L,
                            
                            EndTime = new DateTime(2024, 10, 29, 16, 44, 18, 915, DateTimeKind.Local).AddTicks(5086),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 10, 29, 13, 38, 18, 915, DateTimeKind.Local).AddTicks(5086),
                            State = "CLOSED",
                            UserId = 9
                        },
                        new
                        {
                            Id = 7L,
                            
                            EndTime = new DateTime(2024, 10, 29, 14, 57, 18, 915, DateTimeKind.Local).AddTicks(5100),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 10, 29, 14, 30, 18, 915, DateTimeKind.Local).AddTicks(5100),
                            State = "CLOSED",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8L,
                            
                            EndTime = new DateTime(2024, 10, 29, 14, 52, 18, 915, DateTimeKind.Local).AddTicks(5114),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 10, 29, 13, 25, 18, 915, DateTimeKind.Local).AddTicks(5114),
                            State = "CLOSED",
                            UserId = 1
                        },
                        new
                        {
                            Id = 9L,
                            
                            EndTime = new DateTime(2024, 10, 29, 18, 3, 18, 915, DateTimeKind.Local).AddTicks(5127),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 10, 29, 14, 51, 18, 915, DateTimeKind.Local).AddTicks(5127),
                            State = "CLOSED",
                            UserId = 5
                        },
                        new
                        {
                            Id = 10L,
                            
                            EndTime = new DateTime(2024, 10, 29, 15, 34, 18, 915, DateTimeKind.Local).AddTicks(5143),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 10, 29, 13, 27, 18, 915, DateTimeKind.Local).AddTicks(5143),
                            State = "CLOSED",
                            UserId = 4
                        },
                        new
                        {
                            Id = 11L,
                            
                            EndTime = new DateTime(2024, 10, 29, 14, 58, 18, 915, DateTimeKind.Local).AddTicks(5158),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 10, 29, 13, 24, 18, 915, DateTimeKind.Local).AddTicks(5158),
                            State = "CLOSED",
                            UserId = 3
                        },
                        new
                        {
                            Id = 12L,
                            
                            EndTime = new DateTime(2024, 10, 29, 16, 19, 18, 915, DateTimeKind.Local).AddTicks(5173),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 10, 29, 13, 41, 18, 915, DateTimeKind.Local).AddTicks(5173),
                            State = "CLOSED",
                            UserId = 5
                        },
                        new
                        {
                            Id = 13L,
                            
                            EndTime = new DateTime(2024, 10, 29, 17, 19, 18, 915, DateTimeKind.Local).AddTicks(5191),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 10, 29, 14, 36, 18, 915, DateTimeKind.Local).AddTicks(5191),
                            State = "CLOSED",
                            UserId = 9
                        },
                        new
                        {
                            Id = 14L,
                            
                            EndTime = new DateTime(2024, 10, 29, 16, 55, 18, 915, DateTimeKind.Local).AddTicks(5252),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 10, 29, 14, 30, 18, 915, DateTimeKind.Local).AddTicks(5252),
                            State = "CLOSED",
                            UserId = 7
                        },
                        new
                        {
                            Id = 15L,
                            
                            EndTime = new DateTime(2024, 10, 29, 15, 24, 18, 915, DateTimeKind.Local).AddTicks(5272),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 10, 29, 13, 45, 18, 915, DateTimeKind.Local).AddTicks(5272),
                            State = "CLOSED",
                            UserId = 6
                        },
                        new
                        {
                            Id = 16L,
                            
                            EndTime = new DateTime(2024, 10, 29, 16, 56, 18, 915, DateTimeKind.Local).AddTicks(5288),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 10, 29, 14, 6, 18, 915, DateTimeKind.Local).AddTicks(5288),
                            State = "CLOSED",
                            UserId = 4
                        },
                        new
                        {
                            Id = 17L,
                            
                            EndTime = new DateTime(2024, 10, 29, 17, 26, 18, 915, DateTimeKind.Local).AddTicks(5301),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 10, 29, 14, 18, 18, 915, DateTimeKind.Local).AddTicks(5301),
                            State = "CLOSED",
                            UserId = 4
                        },
                        new
                        {
                            Id = 18L,
                            
                            EndTime = new DateTime(2024, 10, 29, 15, 33, 18, 915, DateTimeKind.Local).AddTicks(5317),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 10, 29, 14, 40, 18, 915, DateTimeKind.Local).AddTicks(5317),
                            State = "CLOSED",
                            UserId = 3
                        },
                        new
                        {
                            Id = 19L,
                            
                            EndTime = new DateTime(2024, 10, 29, 16, 59, 18, 915, DateTimeKind.Local).AddTicks(5330),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 10, 29, 14, 15, 18, 915, DateTimeKind.Local).AddTicks(5330),
                            State = "CLOSED",
                            UserId = 4
                        },
                        new
                        {
                            Id = 20L,
                            
                            EndTime = new DateTime(2024, 10, 29, 15, 17, 18, 915, DateTimeKind.Local).AddTicks(5345),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 10, 29, 14, 40, 18, 915, DateTimeKind.Local).AddTicks(5345),
                            State = "CLOSED",
                            UserId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
