// <auto-generated />
using System;
using CS.Session.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS.Session.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241028181517_AddAuditMetadata")]
    partial class AddAuditMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CS.Session.Domain.Sessions.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MediaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            EndTime = new DateTime(2024, 10, 28, 14, 59, 17, 705, DateTimeKind.Local).AddTicks(215),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 10, 28, 14, 17, 17, 705, DateTimeKind.Local).AddTicks(215),
                            State = "CLOSED",
                            UserId = 3
                        },
                        new
                        {
                            Id = 2L,
                            EndTime = new DateTime(2024, 10, 28, 15, 26, 17, 705, DateTimeKind.Local).AddTicks(343),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 10, 28, 15, 22, 17, 705, DateTimeKind.Local).AddTicks(343),
                            State = "CLOSED",
                            UserId = 10
                        },
                        new
                        {
                            Id = 3L,
                            EndTime = new DateTime(2024, 10, 28, 17, 29, 17, 705, DateTimeKind.Local).AddTicks(364),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 10, 28, 14, 28, 17, 705, DateTimeKind.Local).AddTicks(364),
                            State = "CLOSED",
                            UserId = 10
                        },
                        new
                        {
                            Id = 4L,
                            EndTime = new DateTime(2024, 10, 28, 16, 59, 17, 705, DateTimeKind.Local).AddTicks(384),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 10, 28, 14, 52, 17, 705, DateTimeKind.Local).AddTicks(384),
                            State = "CLOSED",
                            UserId = 6
                        },
                        new
                        {
                            Id = 5L,
                            EndTime = new DateTime(2024, 10, 28, 16, 26, 17, 705, DateTimeKind.Local).AddTicks(403),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 10, 28, 15, 29, 17, 705, DateTimeKind.Local).AddTicks(403),
                            State = "CLOSED",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6L,
                            EndTime = new DateTime(2024, 10, 28, 17, 10, 17, 705, DateTimeKind.Local).AddTicks(499),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 10, 28, 15, 54, 17, 705, DateTimeKind.Local).AddTicks(499),
                            State = "CLOSED",
                            UserId = 9
                        },
                        new
                        {
                            Id = 7L,
                            EndTime = new DateTime(2024, 10, 28, 17, 15, 17, 705, DateTimeKind.Local).AddTicks(522),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 10, 28, 15, 52, 17, 705, DateTimeKind.Local).AddTicks(522),
                            State = "CLOSED",
                            UserId = 10
                        },
                        new
                        {
                            Id = 8L,
                            EndTime = new DateTime(2024, 10, 28, 15, 14, 17, 705, DateTimeKind.Local).AddTicks(542),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 10, 28, 14, 17, 17, 705, DateTimeKind.Local).AddTicks(542),
                            State = "CLOSED",
                            UserId = 5
                        },
                        new
                        {
                            Id = 9L,
                            EndTime = new DateTime(2024, 10, 28, 18, 51, 17, 705, DateTimeKind.Local).AddTicks(563),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 10, 28, 15, 54, 17, 705, DateTimeKind.Local).AddTicks(563),
                            State = "CLOSED",
                            UserId = 9
                        },
                        new
                        {
                            Id = 10L,
                            EndTime = new DateTime(2024, 10, 28, 16, 44, 17, 705, DateTimeKind.Local).AddTicks(587),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 10, 28, 14, 31, 17, 705, DateTimeKind.Local).AddTicks(587),
                            State = "CLOSED",
                            UserId = 4
                        },
                        new
                        {
                            Id = 11L,
                            EndTime = new DateTime(2024, 10, 28, 16, 43, 17, 705, DateTimeKind.Local).AddTicks(609),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 10, 28, 15, 10, 17, 705, DateTimeKind.Local).AddTicks(609),
                            State = "CLOSED",
                            UserId = 6
                        },
                        new
                        {
                            Id = 12L,
                            EndTime = new DateTime(2024, 10, 28, 15, 21, 17, 705, DateTimeKind.Local).AddTicks(631),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 10, 28, 15, 17, 17, 705, DateTimeKind.Local).AddTicks(631),
                            State = "CLOSED",
                            UserId = 5
                        },
                        new
                        {
                            Id = 13L,
                            EndTime = new DateTime(2024, 10, 28, 17, 52, 17, 705, DateTimeKind.Local).AddTicks(651),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 10, 28, 15, 3, 17, 705, DateTimeKind.Local).AddTicks(651),
                            State = "CLOSED",
                            UserId = 3
                        },
                        new
                        {
                            Id = 14L,
                            EndTime = new DateTime(2024, 10, 28, 16, 13, 17, 705, DateTimeKind.Local).AddTicks(674),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 10, 28, 15, 5, 17, 705, DateTimeKind.Local).AddTicks(674),
                            State = "CLOSED",
                            UserId = 5
                        },
                        new
                        {
                            Id = 15L,
                            EndTime = new DateTime(2024, 10, 28, 17, 50, 17, 705, DateTimeKind.Local).AddTicks(696),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 10, 28, 15, 8, 17, 705, DateTimeKind.Local).AddTicks(696),
                            State = "CLOSED",
                            UserId = 6
                        },
                        new
                        {
                            Id = 16L,
                            EndTime = new DateTime(2024, 10, 28, 15, 28, 17, 705, DateTimeKind.Local).AddTicks(718),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 10, 28, 14, 33, 17, 705, DateTimeKind.Local).AddTicks(718),
                            State = "CLOSED",
                            UserId = 2
                        },
                        new
                        {
                            Id = 17L,
                            EndTime = new DateTime(2024, 10, 28, 17, 11, 17, 705, DateTimeKind.Local).AddTicks(740),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 10, 28, 15, 48, 17, 705, DateTimeKind.Local).AddTicks(740),
                            State = "CLOSED",
                            UserId = 2
                        },
                        new
                        {
                            Id = 18L,
                            EndTime = new DateTime(2024, 10, 28, 16, 39, 17, 705, DateTimeKind.Local).AddTicks(763),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 10, 28, 15, 4, 17, 705, DateTimeKind.Local).AddTicks(763),
                            State = "CLOSED",
                            UserId = 2
                        },
                        new
                        {
                            Id = 19L,
                            EndTime = new DateTime(2024, 10, 28, 16, 22, 17, 705, DateTimeKind.Local).AddTicks(784),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 10, 28, 14, 55, 17, 705, DateTimeKind.Local).AddTicks(784),
                            State = "CLOSED",
                            UserId = 1
                        },
                        new
                        {
                            Id = 20L,
                            EndTime = new DateTime(2024, 10, 28, 16, 2, 17, 705, DateTimeKind.Local).AddTicks(806),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 10, 28, 15, 18, 17, 705, DateTimeKind.Local).AddTicks(806),
                            State = "CLOSED",
                            UserId = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
