// <auto-generated />
using System;
using CS.Session.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS.Session.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240918193457_Session-Convert-State-To-String")]
    partial class SessionConvertStateToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CS.Session.Domain.Sessions.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MediaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            EndTime = new DateTime(2024, 9, 18, 18, 6, 56, 822, DateTimeKind.Local).AddTicks(4490),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 18, 16, 43, 56, 822, DateTimeKind.Local).AddTicks(4490),
                            State = "CLOSED",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2L,
                            EndTime = new DateTime(2024, 9, 18, 20, 5, 56, 822, DateTimeKind.Local).AddTicks(4595),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 17, 47, 56, 822, DateTimeKind.Local).AddTicks(4595),
                            State = "CLOSED",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3L,
                            EndTime = new DateTime(2024, 9, 18, 18, 5, 56, 822, DateTimeKind.Local).AddTicks(4611),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 16, 52, 56, 822, DateTimeKind.Local).AddTicks(4611),
                            State = "CLOSED",
                            UserId = 8
                        },
                        new
                        {
                            Id = 4L,
                            EndTime = new DateTime(2024, 9, 18, 19, 32, 56, 822, DateTimeKind.Local).AddTicks(4624),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 18, 17, 30, 56, 822, DateTimeKind.Local).AddTicks(4624),
                            State = "CLOSED",
                            UserId = 10
                        },
                        new
                        {
                            Id = 5L,
                            EndTime = new DateTime(2024, 9, 18, 20, 51, 56, 822, DateTimeKind.Local).AddTicks(4638),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 18, 18, 7, 56, 822, DateTimeKind.Local).AddTicks(4638),
                            State = "CLOSED",
                            UserId = 10
                        },
                        new
                        {
                            Id = 6L,
                            EndTime = new DateTime(2024, 9, 18, 18, 54, 56, 822, DateTimeKind.Local).AddTicks(4655),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 18, 17, 8, 56, 822, DateTimeKind.Local).AddTicks(4655),
                            State = "CLOSED",
                            UserId = 8
                        },
                        new
                        {
                            Id = 7L,
                            EndTime = new DateTime(2024, 9, 18, 19, 12, 56, 822, DateTimeKind.Local).AddTicks(4668),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 18, 16, 53, 56, 822, DateTimeKind.Local).AddTicks(4668),
                            State = "CLOSED",
                            UserId = 10
                        },
                        new
                        {
                            Id = 8L,
                            EndTime = new DateTime(2024, 9, 18, 19, 20, 56, 822, DateTimeKind.Local).AddTicks(4681),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 18, 16, 42, 56, 822, DateTimeKind.Local).AddTicks(4681),
                            State = "CLOSED",
                            UserId = 2
                        },
                        new
                        {
                            Id = 9L,
                            EndTime = new DateTime(2024, 9, 18, 19, 9, 56, 822, DateTimeKind.Local).AddTicks(4693),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 18, 18, 7, 56, 822, DateTimeKind.Local).AddTicks(4693),
                            State = "CLOSED",
                            UserId = 2
                        },
                        new
                        {
                            Id = 10L,
                            EndTime = new DateTime(2024, 9, 18, 19, 42, 56, 822, DateTimeKind.Local).AddTicks(4707),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 18, 18, 9, 56, 822, DateTimeKind.Local).AddTicks(4707),
                            State = "CLOSED",
                            UserId = 2
                        },
                        new
                        {
                            Id = 11L,
                            EndTime = new DateTime(2024, 9, 18, 20, 26, 56, 822, DateTimeKind.Local).AddTicks(4720),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 18, 17, 30, 56, 822, DateTimeKind.Local).AddTicks(4720),
                            State = "CLOSED",
                            UserId = 9
                        },
                        new
                        {
                            Id = 12L,
                            EndTime = new DateTime(2024, 9, 18, 19, 11, 56, 822, DateTimeKind.Local).AddTicks(4735),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 17, 56, 56, 822, DateTimeKind.Local).AddTicks(4735),
                            State = "CLOSED",
                            UserId = 7
                        },
                        new
                        {
                            Id = 13L,
                            EndTime = new DateTime(2024, 9, 18, 20, 32, 56, 822, DateTimeKind.Local).AddTicks(4749),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 17, 20, 56, 822, DateTimeKind.Local).AddTicks(4749),
                            State = "CLOSED",
                            UserId = 3
                        },
                        new
                        {
                            Id = 14L,
                            EndTime = new DateTime(2024, 9, 18, 18, 6, 56, 822, DateTimeKind.Local).AddTicks(4765),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 18, 17, 2, 56, 822, DateTimeKind.Local).AddTicks(4765),
                            State = "CLOSED",
                            UserId = 4
                        },
                        new
                        {
                            Id = 15L,
                            EndTime = new DateTime(2024, 9, 18, 20, 8, 56, 822, DateTimeKind.Local).AddTicks(4827),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 17, 12, 56, 822, DateTimeKind.Local).AddTicks(4827),
                            State = "CLOSED",
                            UserId = 5
                        },
                        new
                        {
                            Id = 16L,
                            EndTime = new DateTime(2024, 9, 18, 19, 17, 56, 822, DateTimeKind.Local).AddTicks(4841),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 18, 17, 22, 56, 822, DateTimeKind.Local).AddTicks(4841),
                            State = "CLOSED",
                            UserId = 4
                        },
                        new
                        {
                            Id = 17L,
                            EndTime = new DateTime(2024, 9, 18, 18, 0, 56, 822, DateTimeKind.Local).AddTicks(4855),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 18, 17, 52, 56, 822, DateTimeKind.Local).AddTicks(4855),
                            State = "CLOSED",
                            UserId = 6
                        },
                        new
                        {
                            Id = 18L,
                            EndTime = new DateTime(2024, 9, 18, 20, 15, 56, 822, DateTimeKind.Local).AddTicks(4869),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 17, 45, 56, 822, DateTimeKind.Local).AddTicks(4869),
                            State = "CLOSED",
                            UserId = 9
                        },
                        new
                        {
                            Id = 19L,
                            EndTime = new DateTime(2024, 9, 18, 18, 21, 56, 822, DateTimeKind.Local).AddTicks(4882),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 18, 17, 25, 56, 822, DateTimeKind.Local).AddTicks(4882),
                            State = "CLOSED",
                            UserId = 6
                        },
                        new
                        {
                            Id = 20L,
                            EndTime = new DateTime(2024, 9, 18, 19, 34, 56, 822, DateTimeKind.Local).AddTicks(4895),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 18, 17, 54, 56, 822, DateTimeKind.Local).AddTicks(4895),
                            State = "CLOSED",
                            UserId = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
