// <auto-generated />
using System;
using CS.Session.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS.Session.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240919065040_Session-EndTime-Nullable")]
    partial class SessionEndTimeNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CS.Session.Domain.Sessions.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MediaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            EndTime = new DateTime(2024, 9, 19, 7, 24, 39, 762, DateTimeKind.Local).AddTicks(8022),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 19, 4, 6, 39, 762, DateTimeKind.Local).AddTicks(8022),
                            State = "CLOSED",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2L,
                            EndTime = new DateTime(2024, 9, 19, 7, 15, 39, 762, DateTimeKind.Local).AddTicks(8127),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 19, 4, 57, 39, 762, DateTimeKind.Local).AddTicks(8127),
                            State = "CLOSED",
                            UserId = 10
                        },
                        new
                        {
                            Id = 3L,
                            EndTime = new DateTime(2024, 9, 19, 7, 40, 39, 762, DateTimeKind.Local).AddTicks(8143),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 19, 4, 50, 39, 762, DateTimeKind.Local).AddTicks(8143),
                            State = "CLOSED",
                            UserId = 9
                        },
                        new
                        {
                            Id = 4L,
                            EndTime = new DateTime(2024, 9, 19, 8, 37, 39, 762, DateTimeKind.Local).AddTicks(8159),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 19, 5, 21, 39, 762, DateTimeKind.Local).AddTicks(8159),
                            State = "CLOSED",
                            UserId = 8
                        },
                        new
                        {
                            Id = 5L,
                            EndTime = new DateTime(2024, 9, 19, 6, 21, 39, 762, DateTimeKind.Local).AddTicks(8173),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 19, 5, 27, 39, 762, DateTimeKind.Local).AddTicks(8173),
                            State = "CLOSED",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6L,
                            EndTime = new DateTime(2024, 9, 19, 6, 15, 39, 762, DateTimeKind.Local).AddTicks(8189),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 19, 4, 42, 39, 762, DateTimeKind.Local).AddTicks(8189),
                            State = "CLOSED",
                            UserId = 5
                        },
                        new
                        {
                            Id = 7L,
                            EndTime = new DateTime(2024, 9, 19, 5, 54, 39, 762, DateTimeKind.Local).AddTicks(8202),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 19, 5, 8, 39, 762, DateTimeKind.Local).AddTicks(8202),
                            State = "CLOSED",
                            UserId = 6
                        },
                        new
                        {
                            Id = 8L,
                            EndTime = new DateTime(2024, 9, 19, 6, 56, 39, 762, DateTimeKind.Local).AddTicks(8215),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 19, 5, 10, 39, 762, DateTimeKind.Local).AddTicks(8215),
                            State = "CLOSED",
                            UserId = 3
                        },
                        new
                        {
                            Id = 9L,
                            EndTime = new DateTime(2024, 9, 19, 4, 19, 39, 762, DateTimeKind.Local).AddTicks(8229),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 19, 4, 7, 39, 762, DateTimeKind.Local).AddTicks(8229),
                            State = "CLOSED",
                            UserId = 10
                        },
                        new
                        {
                            Id = 10L,
                            EndTime = new DateTime(2024, 9, 19, 3, 56, 39, 762, DateTimeKind.Local).AddTicks(8245),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 19, 3, 52, 39, 762, DateTimeKind.Local).AddTicks(8245),
                            State = "CLOSED",
                            UserId = 9
                        },
                        new
                        {
                            Id = 11L,
                            EndTime = new DateTime(2024, 9, 19, 5, 27, 39, 762, DateTimeKind.Local).AddTicks(8259),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 19, 4, 2, 39, 762, DateTimeKind.Local).AddTicks(8259),
                            State = "CLOSED",
                            UserId = 7
                        },
                        new
                        {
                            Id = 12L,
                            EndTime = new DateTime(2024, 9, 19, 8, 26, 39, 762, DateTimeKind.Local).AddTicks(8273),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 19, 5, 8, 39, 762, DateTimeKind.Local).AddTicks(8273),
                            State = "CLOSED",
                            UserId = 3
                        },
                        new
                        {
                            Id = 13L,
                            EndTime = new DateTime(2024, 9, 19, 6, 25, 39, 762, DateTimeKind.Local).AddTicks(8318),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 19, 5, 21, 39, 762, DateTimeKind.Local).AddTicks(8318),
                            State = "CLOSED",
                            UserId = 7
                        },
                        new
                        {
                            Id = 14L,
                            EndTime = new DateTime(2024, 9, 19, 6, 59, 39, 762, DateTimeKind.Local).AddTicks(8334),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 19, 4, 14, 39, 762, DateTimeKind.Local).AddTicks(8334),
                            State = "CLOSED",
                            UserId = 5
                        },
                        new
                        {
                            Id = 15L,
                            EndTime = new DateTime(2024, 9, 19, 7, 10, 39, 762, DateTimeKind.Local).AddTicks(8348),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 19, 4, 7, 39, 762, DateTimeKind.Local).AddTicks(8348),
                            State = "CLOSED",
                            UserId = 9
                        },
                        new
                        {
                            Id = 16L,
                            EndTime = new DateTime(2024, 9, 19, 8, 35, 39, 762, DateTimeKind.Local).AddTicks(8362),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 19, 5, 29, 39, 762, DateTimeKind.Local).AddTicks(8362),
                            State = "CLOSED",
                            UserId = 9
                        },
                        new
                        {
                            Id = 17L,
                            EndTime = new DateTime(2024, 9, 19, 5, 22, 39, 762, DateTimeKind.Local).AddTicks(8375),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 19, 5, 19, 39, 762, DateTimeKind.Local).AddTicks(8375),
                            State = "CLOSED",
                            UserId = 9
                        },
                        new
                        {
                            Id = 18L,
                            EndTime = new DateTime(2024, 9, 19, 6, 58, 39, 762, DateTimeKind.Local).AddTicks(8391),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 19, 4, 3, 39, 762, DateTimeKind.Local).AddTicks(8391),
                            State = "CLOSED",
                            UserId = 1
                        },
                        new
                        {
                            Id = 19L,
                            EndTime = new DateTime(2024, 9, 19, 6, 46, 39, 762, DateTimeKind.Local).AddTicks(8404),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 19, 4, 34, 39, 762, DateTimeKind.Local).AddTicks(8404),
                            State = "CLOSED",
                            UserId = 1
                        },
                        new
                        {
                            Id = 20L,
                            EndTime = new DateTime(2024, 9, 19, 6, 50, 39, 762, DateTimeKind.Local).AddTicks(8418),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 19, 4, 42, 39, 762, DateTimeKind.Local).AddTicks(8418),
                            State = "CLOSED",
                            UserId = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
