// <auto-generated />
using System;
using CS.Session.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS.Session.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240918213745_SessionId-AutGenerated")]
    partial class SessionIdAutGenerated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CS.Session.Domain.Sessions.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MediaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            EndTime = new DateTime(2024, 9, 18, 21, 45, 44, 957, DateTimeKind.Local).AddTicks(1591),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 18, 19, 29, 44, 957, DateTimeKind.Local).AddTicks(1591),
                            State = "CLOSED",
                            UserId = 8
                        },
                        new
                        {
                            Id = 2L,
                            EndTime = new DateTime(2024, 9, 18, 21, 3, 44, 957, DateTimeKind.Local).AddTicks(1692),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 18, 19, 20, 44, 957, DateTimeKind.Local).AddTicks(1692),
                            State = "CLOSED",
                            UserId = 8
                        },
                        new
                        {
                            Id = 3L,
                            EndTime = new DateTime(2024, 9, 18, 22, 54, 44, 957, DateTimeKind.Local).AddTicks(1707),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 18, 19, 46, 44, 957, DateTimeKind.Local).AddTicks(1707),
                            State = "CLOSED",
                            UserId = 10
                        },
                        new
                        {
                            Id = 4L,
                            EndTime = new DateTime(2024, 9, 18, 21, 57, 44, 957, DateTimeKind.Local).AddTicks(1722),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 20, 0, 44, 957, DateTimeKind.Local).AddTicks(1722),
                            State = "CLOSED",
                            UserId = 3
                        },
                        new
                        {
                            Id = 5L,
                            EndTime = new DateTime(2024, 9, 18, 23, 10, 44, 957, DateTimeKind.Local).AddTicks(1735),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 20, 7, 44, 957, DateTimeKind.Local).AddTicks(1735),
                            State = "CLOSED",
                            UserId = 8
                        },
                        new
                        {
                            Id = 6L,
                            EndTime = new DateTime(2024, 9, 18, 20, 15, 44, 957, DateTimeKind.Local).AddTicks(1751),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 18, 19, 38, 44, 957, DateTimeKind.Local).AddTicks(1751),
                            State = "CLOSED",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7L,
                            EndTime = new DateTime(2024, 9, 18, 21, 16, 44, 957, DateTimeKind.Local).AddTicks(1764),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 18, 18, 45, 44, 957, DateTimeKind.Local).AddTicks(1764),
                            State = "CLOSED",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8L,
                            EndTime = new DateTime(2024, 9, 18, 21, 27, 44, 957, DateTimeKind.Local).AddTicks(1777),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 18, 18, 55, 44, 957, DateTimeKind.Local).AddTicks(1777),
                            State = "CLOSED",
                            UserId = 10
                        },
                        new
                        {
                            Id = 9L,
                            EndTime = new DateTime(2024, 9, 18, 21, 10, 44, 957, DateTimeKind.Local).AddTicks(1790),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 18, 18, 47, 44, 957, DateTimeKind.Local).AddTicks(1790),
                            State = "CLOSED",
                            UserId = 9
                        },
                        new
                        {
                            Id = 10L,
                            EndTime = new DateTime(2024, 9, 18, 21, 12, 44, 957, DateTimeKind.Local).AddTicks(1804),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 19, 5, 44, 957, DateTimeKind.Local).AddTicks(1804),
                            State = "CLOSED",
                            UserId = 3
                        },
                        new
                        {
                            Id = 11L,
                            EndTime = new DateTime(2024, 9, 18, 21, 40, 44, 957, DateTimeKind.Local).AddTicks(1818),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 19, 40, 44, 957, DateTimeKind.Local).AddTicks(1818),
                            State = "CLOSED",
                            UserId = 7
                        },
                        new
                        {
                            Id = 12L,
                            EndTime = new DateTime(2024, 9, 18, 23, 3, 44, 957, DateTimeKind.Local).AddTicks(1832),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 18, 20, 4, 44, 957, DateTimeKind.Local).AddTicks(1832),
                            State = "CLOSED",
                            UserId = 7
                        },
                        new
                        {
                            Id = 13L,
                            EndTime = new DateTime(2024, 9, 18, 20, 50, 44, 957, DateTimeKind.Local).AddTicks(1846),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 18, 19, 45, 44, 957, DateTimeKind.Local).AddTicks(1846),
                            State = "CLOSED",
                            UserId = 1
                        },
                        new
                        {
                            Id = 14L,
                            EndTime = new DateTime(2024, 9, 18, 20, 40, 44, 957, DateTimeKind.Local).AddTicks(1861),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 18, 19, 54, 44, 957, DateTimeKind.Local).AddTicks(1861),
                            State = "CLOSED",
                            UserId = 3
                        },
                        new
                        {
                            Id = 15L,
                            EndTime = new DateTime(2024, 9, 18, 19, 2, 44, 957, DateTimeKind.Local).AddTicks(1874),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 18, 18, 58, 44, 957, DateTimeKind.Local).AddTicks(1874),
                            State = "CLOSED",
                            UserId = 8
                        },
                        new
                        {
                            Id = 16L,
                            EndTime = new DateTime(2024, 9, 18, 21, 21, 44, 957, DateTimeKind.Local).AddTicks(1887),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 19, 7, 44, 957, DateTimeKind.Local).AddTicks(1887),
                            State = "CLOSED",
                            UserId = 10
                        },
                        new
                        {
                            Id = 17L,
                            EndTime = new DateTime(2024, 9, 18, 21, 34, 44, 957, DateTimeKind.Local).AddTicks(1901),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 18, 48, 44, 957, DateTimeKind.Local).AddTicks(1901),
                            State = "CLOSED",
                            UserId = 6
                        },
                        new
                        {
                            Id = 18L,
                            EndTime = new DateTime(2024, 9, 18, 21, 31, 44, 957, DateTimeKind.Local).AddTicks(1916),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 18, 59, 44, 957, DateTimeKind.Local).AddTicks(1916),
                            State = "CLOSED",
                            UserId = 3
                        },
                        new
                        {
                            Id = 19L,
                            EndTime = new DateTime(2024, 9, 18, 21, 30, 44, 957, DateTimeKind.Local).AddTicks(1929),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 18, 19, 57, 44, 957, DateTimeKind.Local).AddTicks(1929),
                            State = "CLOSED",
                            UserId = 8
                        },
                        new
                        {
                            Id = 20L,
                            EndTime = new DateTime(2024, 9, 18, 21, 9, 44, 957, DateTimeKind.Local).AddTicks(1942),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 18, 19, 46, 44, 957, DateTimeKind.Local).AddTicks(1942),
                            State = "CLOSED",
                            UserId = 7
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
