// <auto-generated />
using System;
using CS.Session.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS.Session.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CS.Session.Domain.Sessions.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MediaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            EndTime = new DateTime(2024, 9, 18, 8, 55, 11, 517, DateTimeKind.Local).AddTicks(3813),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 18, 7, 33, 11, 517, DateTimeKind.Local).AddTicks(3813),
                            State = 5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 2L,
                            EndTime = new DateTime(2024, 9, 18, 8, 22, 11, 517, DateTimeKind.Local).AddTicks(3947),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 18, 7, 52, 11, 517, DateTimeKind.Local).AddTicks(3947),
                            State = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 3L,
                            EndTime = new DateTime(2024, 9, 18, 8, 14, 11, 517, DateTimeKind.Local).AddTicks(3964),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 7, 49, 11, 517, DateTimeKind.Local).AddTicks(3964),
                            State = 5,
                            UserId = 6
                        },
                        new
                        {
                            Id = 4L,
                            EndTime = new DateTime(2024, 9, 18, 11, 42, 11, 517, DateTimeKind.Local).AddTicks(3977),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 8, 24, 11, 517, DateTimeKind.Local).AddTicks(3977),
                            State = 5,
                            UserId = 10
                        },
                        new
                        {
                            Id = 5L,
                            EndTime = new DateTime(2024, 9, 18, 9, 41, 11, 517, DateTimeKind.Local).AddTicks(3992),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 8, 0, 11, 517, DateTimeKind.Local).AddTicks(3992),
                            State = 5,
                            UserId = 10
                        },
                        new
                        {
                            Id = 6L,
                            EndTime = new DateTime(2024, 9, 18, 9, 49, 11, 517, DateTimeKind.Local).AddTicks(4008),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 18, 7, 47, 11, 517, DateTimeKind.Local).AddTicks(4008),
                            State = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7L,
                            EndTime = new DateTime(2024, 9, 18, 8, 21, 11, 517, DateTimeKind.Local).AddTicks(4022),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 18, 7, 25, 11, 517, DateTimeKind.Local).AddTicks(4022),
                            State = 5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 8L,
                            EndTime = new DateTime(2024, 9, 18, 9, 19, 11, 517, DateTimeKind.Local).AddTicks(4034),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 8, 32, 11, 517, DateTimeKind.Local).AddTicks(4034),
                            State = 5,
                            UserId = 7
                        },
                        new
                        {
                            Id = 9L,
                            EndTime = new DateTime(2024, 9, 18, 8, 38, 11, 517, DateTimeKind.Local).AddTicks(4047),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 18, 8, 7, 11, 517, DateTimeKind.Local).AddTicks(4047),
                            State = 5,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10L,
                            EndTime = new DateTime(2024, 9, 18, 9, 5, 11, 517, DateTimeKind.Local).AddTicks(4060),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 18, 7, 43, 11, 517, DateTimeKind.Local).AddTicks(4060),
                            State = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 11L,
                            EndTime = new DateTime(2024, 9, 18, 11, 50, 11, 517, DateTimeKind.Local).AddTicks(4073),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 18, 8, 36, 11, 517, DateTimeKind.Local).AddTicks(4073),
                            State = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 12L,
                            EndTime = new DateTime(2024, 9, 18, 8, 43, 11, 517, DateTimeKind.Local).AddTicks(4086),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 18, 7, 59, 11, 517, DateTimeKind.Local).AddTicks(4086),
                            State = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 13L,
                            EndTime = new DateTime(2024, 9, 18, 10, 40, 11, 517, DateTimeKind.Local).AddTicks(4100),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 8, 6, 11, 517, DateTimeKind.Local).AddTicks(4100),
                            State = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 14L,
                            EndTime = new DateTime(2024, 9, 18, 9, 38, 11, 517, DateTimeKind.Local).AddTicks(4115),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 8, 23, 11, 517, DateTimeKind.Local).AddTicks(4115),
                            State = 5,
                            UserId = 9
                        },
                        new
                        {
                            Id = 15L,
                            EndTime = new DateTime(2024, 9, 18, 8, 5, 11, 517, DateTimeKind.Local).AddTicks(4190),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 18, 7, 46, 11, 517, DateTimeKind.Local).AddTicks(4190),
                            State = 5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 16L,
                            EndTime = new DateTime(2024, 9, 18, 11, 29, 11, 517, DateTimeKind.Local).AddTicks(4205),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 8, 20, 11, 517, DateTimeKind.Local).AddTicks(4205),
                            State = 5,
                            UserId = 9
                        },
                        new
                        {
                            Id = 17L,
                            EndTime = new DateTime(2024, 9, 18, 10, 36, 11, 517, DateTimeKind.Local).AddTicks(4218),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 7, 42, 11, 517, DateTimeKind.Local).AddTicks(4218),
                            State = 5,
                            UserId = 6
                        },
                        new
                        {
                            Id = 18L,
                            EndTime = new DateTime(2024, 9, 18, 9, 20, 11, 517, DateTimeKind.Local).AddTicks(4232),
                            MediaId = 1,
                            StartTime = new DateTime(2024, 9, 18, 8, 25, 11, 517, DateTimeKind.Local).AddTicks(4232),
                            State = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 19L,
                            EndTime = new DateTime(2024, 9, 18, 8, 35, 11, 517, DateTimeKind.Local).AddTicks(4245),
                            MediaId = 2,
                            StartTime = new DateTime(2024, 9, 18, 8, 10, 11, 517, DateTimeKind.Local).AddTicks(4245),
                            State = 5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 20L,
                            EndTime = new DateTime(2024, 9, 18, 10, 16, 11, 517, DateTimeKind.Local).AddTicks(4258),
                            MediaId = 3,
                            StartTime = new DateTime(2024, 9, 18, 7, 39, 11, 517, DateTimeKind.Local).AddTicks(4258),
                            State = 5,
                            UserId = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
