version: '3'
services:
  redis.cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  redis.queue:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"