// <auto-generated />
using CS.User.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS.User.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CS.User.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john-1.doe-1@fakemail12.com",
                            Name = "John-1",
                            Surname = "Doe-1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "john-2.doe-2@fakemail12.com",
                            Name = "John-2",
                            Surname = "Doe-2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "john-3.doe-3@fakemail12.com",
                            Name = "John-3",
                            Surname = "Doe-3"
                        },
                        new
                        {
                            Id = 4,
                            Email = "john-4.doe-4@fakemail12.com",
                            Name = "John-4",
                            Surname = "Doe-4"
                        },
                        new
                        {
                            Id = 5,
                            Email = "john-5.doe-5@fakemail12.com",
                            Name = "John-5",
                            Surname = "Doe-5"
                        },
                        new
                        {
                            Id = 6,
                            Email = "john-6.doe-6@fakemail12.com",
                            Name = "John-6",
                            Surname = "Doe-6"
                        },
                        new
                        {
                            Id = 7,
                            Email = "john-7.doe-7@fakemail12.com",
                            Name = "John-7",
                            Surname = "Doe-7"
                        },
                        new
                        {
                            Id = 8,
                            Email = "john-8.doe-8@fakemail12.com",
                            Name = "John-8",
                            Surname = "Doe-8"
                        },
                        new
                        {
                            Id = 9,
                            Email = "john-9.doe-9@fakemail12.com",
                            Name = "John-9",
                            Surname = "Doe-9"
                        },
                        new
                        {
                            Id = 10,
                            Email = "john-10.doe-10@fakemail12.com",
                            Name = "John-10",
                            Surname = "Doe-10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
