// <auto-generated />
using System;
using CS.Media.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS.Media.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CS.Media.Domain.Medias.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LengthInSeconds")
                        .HasColumnType("int");

                    b.Property<int>("MediaTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MediaTypeId");

                    b.ToTable("Medias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MediaTypeId = 3,
                            Name = "EPG"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthInSeconds = 9848,
                            MediaTypeId = 1,
                            Name = "VOD-2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthInSeconds = 11899,
                            MediaTypeId = 1,
                            Name = "VOD-3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthInSeconds = 5433,
                            MediaTypeId = 1,
                            Name = "VOD-4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthInSeconds = 6683,
                            MediaTypeId = 1,
                            Name = "VOD-5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthInSeconds = 9477,
                            MediaTypeId = 1,
                            Name = "VOD-6"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthInSeconds = 8174,
                            MediaTypeId = 1,
                            Name = "VOD-7"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthInSeconds = 10016,
                            MediaTypeId = 1,
                            Name = "VOD-8"
                        },
                        new
                        {
                            Id = 9,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthInSeconds = 14242,
                            MediaTypeId = 1,
                            Name = "VOD-9"
                        },
                        new
                        {
                            Id = 10,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthInSeconds = 14018,
                            MediaTypeId = 1,
                            Name = "VOD-10"
                        },
                        new
                        {
                            Id = 11,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthInSeconds = 6016,
                            MediaTypeId = 1,
                            Name = "VOD-11"
                        },
                        new
                        {
                            Id = 12,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthInSeconds = 2952,
                            MediaTypeId = 2,
                            Name = "AOD-12"
                        },
                        new
                        {
                            Id = 13,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthInSeconds = 645,
                            MediaTypeId = 2,
                            Name = "AOD-13"
                        },
                        new
                        {
                            Id = 14,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthInSeconds = 1869,
                            MediaTypeId = 2,
                            Name = "AOD-14"
                        },
                        new
                        {
                            Id = 15,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthInSeconds = 1373,
                            MediaTypeId = 2,
                            Name = "AOD-15"
                        },
                        new
                        {
                            Id = 16,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthInSeconds = 1608,
                            MediaTypeId = 2,
                            Name = "AOD-16"
                        },
                        new
                        {
                            Id = 17,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthInSeconds = 2586,
                            MediaTypeId = 2,
                            Name = "AOD-17"
                        },
                        new
                        {
                            Id = 18,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthInSeconds = 3371,
                            MediaTypeId = 2,
                            Name = "AOD-18"
                        },
                        new
                        {
                            Id = 19,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthInSeconds = 803,
                            MediaTypeId = 2,
                            Name = "AOD-19"
                        },
                        new
                        {
                            Id = 20,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthInSeconds = 689,
                            MediaTypeId = 2,
                            Name = "AOD-20"
                        },
                        new
                        {
                            Id = 21,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthInSeconds = 2910,
                            MediaTypeId = 2,
                            Name = "AOD-21"
                        },
                        new
                        {
                            Id = 22,
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthInSeconds = 3473,
                            MediaTypeId = 2,
                            Name = "AOD-22"
                        });
                });

            modelBuilder.Entity("CS.Media.Domain.Medias.MediaType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MediaTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LongName = "Video on Demand",
                            Name = "VOD"
                        },
                        new
                        {
                            Id = 2,
                            LongName = "Audio on Demand",
                            Name = "AOD"
                        },
                        new
                        {
                            Id = 3,
                            LongName = "Electronic Program Guide",
                            Name = "EPG"
                        });
                });

            modelBuilder.Entity("CS.Media.Domain.Medias.Media", b =>
                {
                    b.HasOne("CS.Media.Domain.Medias.MediaType", "MediaType")
                        .WithMany()
                        .HasForeignKey("MediaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaType");
                });
#pragma warning restore 612, 618
        }
    }
}
